# PostgreSQL DataSource for DR storage backend
forage.jdbc.db.kind=postgresql
forage.jdbc.url=jdbc:postgresql://localhost:5432/postgres
forage.jdbc.username=test
forage.jdbc.password=test

# Connection pool
forage.jdbc.pool.initial.size=2
forage.jdbc.pool.min.size=1
forage.jdbc.pool.max.size=5
